### ISSUE TITLE
Create control plane in AWS using bosh bootloader

### ISSUE THREAD

**Issue by amlan-pivotal** [amlan-pivotal/install-pas#4]
AS A/AN operator
I NEED a setup a control plane which will include a Jumpbox, BOSH director and NAT instance
SO THAT I install Concourse to manage PCF platform

**Comment by amlan-pivotal** [comment]
Refer: #3 

* Configure AWS - Provide access key, secret,  default region
* Create aws user account in AWS for managing Control plane
* Create aws policy for the user account
* Create aws access keys for the user account

For the above refer ???????

**Comment by amlan-pivotal** [comment]
* Once the 3 VMs are up, `eval "$(bbl print-env)"`  to load secret credentials for the VMs to environment variable.

* Review cloud config using `bosh cloud-config`
* Update cloud config using `bosh update-cloud-config cloud-config.yml`

**Comment by amlan-pivotal** [comment]
* Upload stemcell
```
bosh upload-stemcell https://s3.amazonaws.com/bosh-core-stemcells/aws/bosh-stemcell-97.16-aws-xen-hvm-ubuntu-xenial-go_agent.tgz
```
* Check `bosh stemcells`

**Comment by amlan-pivotal** [comment]
* Configure Load balancer for Concourse
#Ensure BBL environment variables are loaded: +BBL_AWS_REGION +BBL_AWS_SECRET_ACCESS_KEY +BBL_IAAS

```
bbl plan
cp $HOME/vendors/concourse-credhub/bbl-terraform/aws/concourse-lb_override.tf terraform/
bbl up
```

**Comment by amlan-pivotal** [comment]
* **How to increase ephimeral disk of worker?**
  - First get the cloud-config `bosh cloud-config`
  - Modify cloud config
  - Update cloud-config `bosh update-cloud-config my-cloud-config.yml'
  - Download latest manifect `bosh -d concourse manifest > concourse-manifest.yml'
  - Deploy using `bosh -d concourse deploy concourse-manifest.yml`

Modified cloud-config
```
- cloud_properties:
    ephemeral_disk:
      size: 102400
      type: gp2
    instance_type: m4.4xlarge
  name: extra-large
```

**Comment by amlan-pivotal** [comment]
* **How to add additional worker?**
  - Download latest manifest `bosh -d concourse manifest > concourse-manifest.yml'
  - Modify no. of instances in manifest
  - Deploy using `bosh -d concourse deploy concourse-manifest.yml`

Modified manifest
```
- azs:
  - z1
  instances: 3
  jobs:
  - consumes:
      baggageclaim:
        from: worker-baggageclaim
    name: worker
    properties:
      drain_timeout: 10m
      tsa:
        worker_key: ((worker_key))
    release: concourse
  - name: baggageclaim
    properties:
      log_level: debug
    provides:
      baggageclaim:
        as: worker-baggageclaim
    release: concourse
  - name: garden
    properties:
      garden:
        listen_address: 0.0.0.0:7777
        listen_network: tcp
    release: garden-runc
  name: worker
```

* **How to recreate all VMs during deployment?**
  - Deploy using `bosh -d concourse deploy concourse-manifest.yml --recreate`
This is useful to flush persistence disk
